### PR TITLE
Drop Python 2.6 testing.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by zerok** [comment]
Thanks :) Next we should really start updating this for newer versions of Django and Python 3.4+ ;-)

**Comment by timgraham** [comment]
Yes, I was thinking about doing that, but it's unclear to me what the testing situation is. There are these Travis/tox files, but it seems like they don't actually work?

**Comment by zerok** [comment]
I noticed that, too, while reviewing your PR :-/ Looks like testing has been neglected for quite some time now. If I can find the time tomorrow I'll try to get the tests working again.

**Comment by zerok** [comment]
OK, am down to 1 error now. Should be done with that tomorrow.

**Pull request merged**
